In [3]:
import numpy as np

A = np.array([[56.0,0.0,4.4, 68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = 100*A.sum(axis=0)
print(cal)

[ 5900. 23900. 15540.  7690.]


In [7]:
percentage = A/cal.reshape(1,4)
print(percentage)

[[0.00949153 0.         0.00028314 0.00884265]
 [0.00020339 0.00435146 0.0033462  0.00104031]
 [0.00030508 0.00564854 0.00637066 0.00011704]]
